### ISSUE TITLE
又来打扰了，Action执行出错了

### ISSUE THREAD

**Issue by telami** [zhuorantan/SQLiteCipher#2]
CocoaPods 1.15.0 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org/ and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0

[!] CocoaPods could not find compatible versions for pod "SQLite.swift/SQLCipher":
  In Podfile:
    SQLite.swift/SQLCipher (= 0.15.0)

None of your spec sources contain a spec satisfying the dependency: `SQLite.swift/SQLCipher (= 0.15.0)`.

**Comment by telami** [comment]
<img width="618" alt="image" src="https://github.com/zhuorantan/SQLiteCipher/assets/25978237/d40a7ce6-c462-4e2d-a9ed-ea1c4e372e5d">
使用模拟器时，还有这个错误

**Comment by zhuorantan** [comment]
`SQLite.swift` hasn't published `0.15.0` to CocoaPods yet, as https://cocoapods.org/pods/SQLite.swift currently shows `0.14.1` as the latest version. I have updated the script to pull the pod from git to work around it.
